[build]
  publish = "public"
  functions = "netlify/functions"
[functions]
  node_bundler = "esbuild"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
[[redirects]]
  from = "/blog/:article"
  to = "/blog/:article.html"
  status = 301
  force = false
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:;"